version: "1.0.0"
services:
  - type: web
    name: Random-5542891837
    runtime: docker
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

    envVars:
      - key: SESSION_ID
        sync: false
      - key: TIMEZONE
        sync: false
      - key: PREFIX
        sync: false
      - key: DASHBOARD_USER
        sync: false
      - key: DASHBOARD_PASS
        sync: false
      - key: server_port
        value: "3010"
